const base = {
    // baseUrl:'http://localhost:5000',
    // baseUrl:'http://192.168.1.241:5000',
    baseUrl:'',
    login:'/admin/login',
    islogin:'/admin/islogin',
    gettouxiang:'/admin/gettouxiang',
    logout:'/admin/logout',
    adminisregist:'/admin/adminisregist',
    adminregist:'/admin/adminregist',
    updateadmin:'/admin/updateadmin',
    updatepassword:'/admin/updatepassword',
    getarticle:'/admin/getarticle',
    forbidarticle:'/admin/forbidarticle',
    getagument:'/admin/getagument',
    forbidagument:'/admin/forbidagument',
    forbidchildagu:'/admin/forbidchildagu',
    notify:'/admin/notify',
    getfeedback:'/admin/getfeedback',
    resovlefeedback:'/admin/resovlefeedback',
    getadminusers:'/admin/getadminusers',
    forbidadmin:'/admin/forbidadmin',
    updateadminlevel:'/admin/updateadminlevel',
    stuserinfo:'/admin/stuserinfo',
    stuseragument:'/admin/stuseragument',
    stuserfollow:'/admin/stuserfollow',
    stuserbyfollow:'/admin/stuserbyfollow',
    stuserlike:'/admin/stuserlike',
    stuserpage:'/admin/stuserpage',
    stpageinfo:'/admin/stpageinfo',
    stpageagument:'/admin/stpageagument',
    stpagelike:'/admin/stpagelike',
    stcomponent:'/admin/stcomponent',
    randomkey:'/admin/randomkey',
    savemicor:'/admin/savemicor',
    getmicor:'/admin/getmicor',
    updatelooker:'/admin/updatelooker',
};

export default base;