const base = {
    // baseUrl:'http://localhost:5000',
    // baseUrl:'http://192.168.1.241:5000',
    baseUrl:'',

    login:'/api/login',
    islogin:'/api/islogin',
    logout:'/api/logout',
    isregist:'/api/isregist',
    regist:'/api/regist',
    updateuser:'/api/updateuser',
    updatepassword:'/api/updatepassword',
    availableurl:'/api/availableurl',
    showcomponent:'/api/showcomponent',
    savepage:'/api/savepage',
    publish:'/api/publish',
    querydraft:'/api/querydraft',
    deletepage:'/api/deletepage',
    querypage:'/api/querypage',
    querypageandwriter:'/api/querypageandwriter',
    querypagebyversion:'/api/querypagebyversion',
    loadmoreagument:'/api/loadmoreagument',
    querypublish:'/api/querypublish',
    updatepublish:'/api/updatepublish',
    updatelookuser:'/api/updatelookuser',
    addpagelike:'/api/addpagelike',
    addfollow:'/api/addfollow',
    addagument:'/api/addagument',
    addchildagu:'/api/addchildagu',
    getaction:'/api/getaction',
    queryuppage:'/api/queryuppage',
    queryuagument:'/api/queryuagument',
    queryubyfollow:'/api/queryubyfollow',
    getfirstmessage:'/api/getfirstmessage',
    getmessages:'/api/getmessages',
    getnoreadmun:'/api/getnoreadmun',
    markread:'/api/markread',
    markreadbyid:'/api/markreadbyid',
    userbaseinfo:'/api/userbaseinfo',
    categorytopfive:'/api/categorytopfive',
    serchpage:'/api/serchpage',
    followtop:'/api/followtop',
    savetemp:'/api/savetemp',
    queryhavetemp:'/api/queryhavetemp',
    querytemp:'/api/querytemp',
    deletetemp:'/api/deletetemp',
    images:'/api/images',
    feedback:'/api/feedback',
};

export default base;